### ISSUE TITLE
gmail Problems

### ISSUE THREAD

**Issue by sebastian-schmitt** [vert-x3/vertx-mail-client#113]
Dear vertx-team,

I'm a big fan of your libraries - thanks for your great work!

Recently, I stumbled upon a (hopefully) small issue:

After upgrading from 3.8.0 to 3.8.1 speaking the smtp protocol with gmail is not working anymore.

I tried different parameter settings and finally got back to my initial (working) one:

```
ssl: true
starttls: optional
port: 465
host: smtp.gmail.com
user: <user>@gmail.com
password: <App Password, generated after enabling 2-Step-Authentication at the google-account-side>
```

Trying to send a mail using these, I receive a "AUTH XOAUTH2 failed 535-5.7.8 Username and Password not accepted". 

Switching back to ~~3.8.0~~ 3.7.1 solves this issue.

**Comment by gaol** [comment]
From `3.8.0+`, `XOAUTH2` was included(please see PR: https://github.com/vert-x3/vertx-mail-client/pull/94) and is the preference authenticate method. In this case, you need access token instead of generated app password to login.

You can also call like: `new MailConfig().setAuthMethods("PLAIN")` to bypass the `XOAUTH2` to use `username` and `password` to login.

**Comment by sebastian-schmitt** [comment]
oh great - thank you very much!
