### ISSUE TITLE
Kotlin: sendMail hangs when used in runBlocking

### ISSUE THREAD

**Issue by AxelG1** [vert-x3/vertx-mail-client#137]
Encountered in 3.8.3 (I know it's not the latest, but maybe it's worth knowing)

I used `io.vertx.ext.mail.MailClient.sendMail` inside `runBlocking` because then, I though it would be neat to have the method's result before ending. 

Interestingly, it worked as expected locally in my development environment (Intellij), but hanged when deployed as a fat jar to an instance of the Docker image `vertx/vertx3-exec:3.8.3`. Therefore I cannot claim that it's easy to reproduce.

In similar situations e.g. with `io.vertx.ext.web.client.WebClient.post` things resolved as expected.

JVM is 1.8

**Comment by gaol** [comment]
`io.vertx.ext.mail.MailClient.sendMail` is designed to be a non-blocking API, running it inside a `runBlocking` call doesn't make sense(I maybe wrong because I don't know much about Kotlin). I am actually curious how you deal with the `Handler<AsyncResult<MailResult>>` within `runBlocking` ? :)

`io.vertx.ext.web.client.WebClient.post` returns an instance of `HttpRequest<Buffer>`, only call on `sendXXX` methods sends the request.

**Comment by gaol** [comment]
I am closing it, please re-open it if you still have the issue.
