### ISSUE TITLE
Do we really need idle timeout?

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-mail-client#16]
None of our other clients to do this.

**Comment by alexlehm** [comment]
I would like to argue that this is useful and it might be a good idea to support a similar thing in other clients as well (e.g. http keep-alive). When using a service only occasionally, for example sending out a mail at given intervals like every hour or every day (like a cronjob), the connection pool will stay active unless the server times out the connection, which is not good since a firewall might shut down the connection after while (like after 2 or 4 hours) and the connection will have to be re-established, I would prefer to get ahead of that and close the idle connection in the client as well.
For database connections, that would also be useful, connections that are idle for a long time might also cause problems.
I can take the function out if you decide so, but I would prefer to keep support in (plus I fixed my bug in the timer code, and its now working properly :-) )

**Comment by purplefox** [comment]
I think this just overcomplicates things. If the user doesn't want to keep connections open they can just set keep-alive to false.

**Comment by alexlehm** [comment]
commmit de15f6903900ccfe40aa61fe014bf41858c74a33
removed idle timeout function

**Comment by alexlehm** [comment]
due to a merge mixup from me this didn't end up in the 3.0.0 version, i.e. the code is still included in 3.0.0, but the documentation is removed. I will remove the code again for a new pr

**Comment by alexlehm** [comment]
fixed with commit 032c00a411cd588f4e4ca54e261e332c679ee19e
sorry about the mixup before
