### ISSUE TITLE
Can I use this to find out if the recipient address exists?

### ISSUE THREAD

**Issue by thokari** [vert-x3/vertx-mail-client#55]
The MailResult that I am getting does not tell me much in that regard, existing and non-existing addresses seem undistinguishable... I am now doing MX record lookup and then connecting directly, but is there a simpler way?

**Comment by alexlehm** [comment]
The mail module is a smtp client, not a router, so you will usually not get a result if an address exists only that your smtp server has accepted the RCPT TO command for this user.
Even when you have to mx server accept the address, this is not a sure indication that the address exists, a server might not return an error even for nonexistent addresses for security reasons or the mail might get queued but then returned due to quota exceeded or something.

There are basically two reasons why the mail client is not a router, first of all it does not use MX lookup, it uses a single smtp server as a smarthost (you could implement that yourself), MX routing might not be available for a couple of reasons. The 2nd reason is the client does not implement a queue, so sending mails to the MX server of the recipient will fail if the server is currently not available, to do that properly backup MX should be used if the primary MX is unreachable and the mails have to be queued for a few days in case of a soft smtp error (4xx). This all is outside the scope of a smtp client IMHO and is better left to a postfix or other mail server running in the local network.
