### ISSUE TITLE
add support for proxy setting in NetClient

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-mail-client#79]

**Comment by vietj** [comment]
Current net client supports proxies, can we have this implemented ?

**Comment by sfitts** [comment]
We need this support as well.  Looks like all it would take is to add the ability to provide a net clients doc as part of the MailConfig object (and then use that when creating the NetClient in addition to cherry-picking the SSL settings).

**Comment by vietj** [comment]
do you mind contributing @sfitts ?

**Comment by sfitts** [comment]
@vietj let me see what I can do.  If I can get you a PR can you put it in a patch to 3.6?  I'd like to get this into our current version and we can't move to 3.7 until our next release.

**Comment by sfitts** [comment]
2 questions...

1) The usual pattern followed in these cases would be to have `MailConfig` subclass from `NetClientOptions`.  Is that something you would put in 3.6.x?  In 3.7?  Not at all?  Not sure what the bar is for changes of that kind.

1) If we assume that the MailConfig contains a NetClientOptions (instead of sub-classing) there is the issue of the overlapping options.  There are 4 of these (ssl, trustAll, and 2 keystore options).  One approach would be to say that MailConfig settings (default or otherwise) always overwrite those that might be in the NetClientOptions.  The other would be to get tricky and have them only overwrite if they were explicitly set.

TIA for the advice.

**Comment by vietj** [comment]
@sfitts 3.7 would be fine I think

I think that we can try subclassing, that's how it's done in `WebClientOptions` and a few others.

**Comment by sfitts** [comment]
Will -- do.  But if it is possible to put in 3.6.4 I would appreciate it.

**Comment by pmlopes** [comment]
@vietj @sfitts if subclassing is the desired option, then I think we should apply the same pattern to other projects too, out of my head I can think of `Redis` and `OAuth2` which require net client options and where using this as a property. The only annoyance with subclassing is that you need to override the whole class to keep the fluent builder pattern intact with the new type. Which means that if the parent type changes, we will need to revisit all the children and update.

**Comment by vietj** [comment]
@pmlopes it depends on which project for some it does not make sense. We can change the existing ones if that does not break compatiblitly.

**Comment by sfitts** [comment]
We also don't use those clients so I'm not sure I'm the best one to make any changes...

I'm also happy to reimplement this without sub-classing if that is the preference (we'd just like to get this done in some form since we have an upcoming customer deployment that requires it and we're stuck without some solution).

**Comment by pmlopes** [comment]
I see that pgclient also subclasses, I guess we could standardize on subclassing for consistency.

**Comment by vietj** [comment]
yes subclassing in practice works well, although I remember a case where it wasn''t makeing sense.

WebClientOptions also extends HttpClientOptions
